153 andrew cart end
KyleMcMullin/CS3450-Group7 pull request #204
Opened 2022-11-26 19:50 UTC by awilki435

Closes issues 193 and 184

2022-11-27 04:55 UTC, KuzonFyre requested changes

2022-11-27 04:55 UTC, KuzonFyre commented on androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/viewmodels/CartScreenViewModel.kt
> +    fun checkInventory(){
The price needs to be calculated based off the cost of all the ingredients of EACH drink in the cart. As far as I can tell this is only doing it based off one.

2022-11-27 04:55 UTC, KuzonFyre commented on androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/viewmodels/CartScreenViewModel.kt
> +    fun checkInventory(){
We also need to account for quantity of the drinks. There should be a total count of the correct number of drinks in the cart.

2022-11-27 23:11 UTC, KuzonFyre commented
Still need to calculate cost correctly with quantity

2022-11-30 03:03 UTC, ablibranix approved these changes

2022-11-30 07:23 UTC, merged